name: Build LinConsol-Executable

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    strategy:
      matrix:
        runtime: [win-x64, win-x86]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.303'

      - name: Build project (${{ matrix.runtime }})
        run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true -o ./Exports/${{ matrix.runtime }} -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true

      - name: Add software license
        run: cp LICENSE ./Exports/${{ matrix.runtime }}/LICENSE.txt

      - name: Upload artifacts (${{ matrix.runtime }})
        uses: actions/upload-artifact@v3
        with:
          name: linconsol_${{ matrix.runtime }}
          path: ./Exports/${{ matrix.runtime }}
